services:

  db:
    image: mysql:9.7
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-test-track}
      MYSQL_PASSWORD: ${DB_PASSWORD:-test-track}
      MYSQL_USER: ${DB_USER:-test-track}
      MYSQL_DATABASE: ${DB_DATABASE:-test-track}
    ports:
      - ${DB_PORT:-3306}:3306


volumes:
  dbdata: